# The name of the device as you want it to appear in teh reports
device_name: OMX-V4
# What is the location of the device
device_location: MRI-IGH
# What type of device. This should be matching the name of the module defining this type of microscope
device_type: 3d-sim
device_version: 4
config_version: 1

channels:
  # How is channel referred in the file name. List of strings
  # eg. 'My_file_name_A647_Cy3_FITC_DAPI_and_the_end.tif'
  names: ["DAPI", "FITC", "Cy3", "A647"]
  # Wavelengths of the specified channels
  excitation_wavelengths: [405, 488, 561, 642]
  emission_wavelengths: [425, 525, 600, 680]

objectives:
  # How is the objective referred in the file name. List of strings
  names: ["10xAir", "20xOil", "60xSil", "60xOil", "100xOil", "100xTIRF"]
  # The objective lens magnification. List of integers
  objective_lens_nominal_magnification: [10, 20, 60, 60, 100, 100]
  # The objective lens immersion medium refractive index. List of floats
  objective_lens_refractive_index: [1.0, 1.518, 1.47, 1.516, 1.510, 1.516]
  # The objective lens NA. List of floats
  objective_lens_na: [0.4, 0.8, 1.3, 1.42, 1.4, 1.49]
