MAIN:
  metrics_tag_id = 132
  config_version = 0.1

DELETION:

MICROSCOPE:
  type: 3D-SIM
  version: 4

WAVELENGTHS:
  excitation: [405, 488, 561, 642]
  emission: [425, 525, 600, 680]

OBJECTIVES:
  magnifications: [60, 100]

EXCITATION_POWER:
  do_laser_power_measurement: false
  laser_power_measurement_wavelengths: [405, 488, 532, 561, 642]
  laser_power_measurement_units: mW

ARGOLIGHT:
  do_spots: true
  spots_image_tag: Argo-SIM_B
  remove_cross: false
  spots_distance: 5.0
  # sigma: [1, 2, 2]
  lower_threshold_correction_factors: [0.4, 0.5, 0.5, 0.5]
  upper_threshold_correction_factors: [0.45, 0.7, 0.7, 0.7]
  do_vertical_resolution: true
  vertical_res_image_tag: Argo-SIM_E_0deg
  do_horizontal_resolution: true
  horizontal_res_image_tag: Argo-SIM_E_90deg
  res_method: rayleight
  res_measurement_band: 0.2
